name: portfolio_update
description: My personal portfolio 2022

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.8.1
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.5
  bouncing_widget: ^2.0.0
  animated_text_kit: ^4.2.2
  get_storage: ^2.1.1
  blobs: ^2.0.0
  coast: ^2.0.2
  anitex: ^3.0.1
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.1.11
  lottie: ^2.4.0
  dio: ^5.2.1+1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
#  motion: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/jpg/
    - assets/lottie/
    - assets/game/
    - assets/game/cacti/
    - assets/game/dino/
    - assets/game/ptera/

  fonts:
    - family: Joyride
      fonts:
        - asset: assets/font/Joyride.otf
    - family: Joyride Outline
      fonts:
        - asset: assets/font/Joyride-Outline.otf